################################################################################
#
# Copyright (C) BadPixxel <www.badpixxel.com>
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
################################################################################

################################################################
# Defined Pipeline Stages
stages:
  - quality
  - deploy
  - dependencies

################################################################
# Functional Tests
################################################################

.quality_tests:    &quality_tests
    stage:      quality
    tags:       [ Dedicated ]
    before_script:
        # Build from Sources
        - echo "phar.readonly=0" >> /usr/local/etc/php/conf.d/phar.ini
    script:
        # Build from Sources
        - composer update
        - php wall-e.php self:build
        - php wall-e.php self:install
        # Show Commands List
        - wall-e list
        # Execute GrumpPhp Testsuite
        - wall-e grumphp:quality
        - wall-e grumphp:stan
        - wall-e grumphp:full

quality:php-8.2:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
    <<: *quality_tests

quality:php-8.1:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    <<: *quality_tests

quality:php-8.0:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    <<: *quality_tests

quality:php-7.4:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4
    <<: *quality_tests

#################################################################
## Build Documentation
#################################################################
pages:
    image:      jekyll/jekyll:latest
    stage:      deploy
    tags:       [ Dedicated-Docker ]
    ################################################################################
    # Run Test Script
    script:
        - wget -qO - https://gitlab.com/badpixxel-robo/jekyll/-/raw/main/scripts/gitlab-pages.sh | sh
    artifacts:
        paths:
            - public

#################################################################
## Trigger Php SDK Docker Build
#################################################################
docker:php-sdk:
    stage:      dependencies
    trigger:
        project:  badpixxel-projects/Php-Sdk
        strategy: depend

