
################################################################################
#
# Copyright (C) 2020 BadPixxel <www.badpixxel.com>
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
################################################################################

################################################################################
# Docker Compose File
################################################################################

name: "Wall-E"

services:

    ################################################################################
    # PHP 8.4
    php-8.4:
        image:              registry.gitlab.com/badpixxel-projects/php-sdk:php-8.4
        container_name:     php84.badpixxel.wall-e.local
        environment:
            PHP_CS_FIXER_IGNORE_ENV: 1
        volumes:
            - ./:/var/www/html
            - vendor-php84:/var/www/html/vendor

    ################################################################################
    # PHP 8.3
    php-8.3:
        image:              registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3
        container_name:     php83.badpixxel.wall-e.local
        volumes:
            - ./:/var/www/html
            - vendor-php83:/var/www/html/vendor

    ################################################################################
    # PHP 8.2
    php-8.2:
        image:              registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
        container_name:     php82.badpixxel.wall-e.local
        volumes:
            - ./:/var/www/html
            - vendor-php82:/var/www/html/vendor

volumes:
    vendor-php84: ~
    vendor-php83: ~
    vendor-php82: ~